version: "3.7"
services:
    g2p-frysk:
       image: "${APPNAME}:${VERSION}"
       deploy:
          replicas: 1
          resources:
             limits:
                memory: "3GB"
       ports:
          - "10001:3838"
       networks:
          - ${APPNAME}
networks:
    g2p-frysk:
